require: rubocop-rspec

AllCops:
  UseCache: true
  Exclude:
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'config/environments/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 200

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/**/*.rb'

RSpec/ExpectInHook:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/MessageSpies:
  EnforcedStyle: receive

Layout/AlignHash:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false
